[package]
name = "nareswara-dark-theme"
version = "0.0.1"
edition = "2021"
authors = ["Rifai Nareswara"]
description = "Nareswara Dark theme for Zed :)"
repository = "https://github.com/rifainareswara/nareswara-dark-theme"

[dependencies]
zed_extension_api = "0.3.0"

[lib]
crate-type = ["cdylib"]
